### ISSUE TITLE
Need tf 1.14-compatible commits

### ISSUE THREAD

**Issue by cjolivier01** [pytorch/xla#1552]
## ❓ Questions and Help
Hi, I have been spending significant effort for several weeks trying to find pytorch and xla commits that work with the released version of tensorflow 1.14 and with each other.

Can you please help?  Latest issues (not the only one) is getting things like this:
```cpp
/home/cjolivier01/src/my_pytorch/pytorch/aten/src/ATen/Context.h:5:10: fatal error: 'ATen/TypeExtendedInterface.h' file not found
#include <ATen/TypeExtendedInterface.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
ATen/C10 headers seem to change daily?  It's not clear why it's so hard to find a combination that will compile at all.  Can you give me some insight possibly how to find one?

Thanks,

-Chris

**Comment by cjolivier01** [comment]
Other ones like this (I keep adding include dirs to setup.py but not clear why this doesnt work automaticallt):

```cpp
/home/chriso/src/clion_pytorch_stuff/pytorch/xla/torch_xla/csrc/aten_xla_type_default.h:76:80: error: no type named 'IntArrayRef' in                                                           
      namespace 'at'
  static at::Tensor & as_strided_(at::Tensor & self, at::IntArrayRef size, at::IntArrayRef stride, c10::optional<int64_t> storage_offset);
                                                                           ~~~~^
/home/chriso/src/clion_pytorch_stuff/pytorch/xla/torch_xla/csrc/aten_xla_type_default.h:131:66: error: no type named 'IntArrayRef' in                                                          
      namespace 'at'
  static at::Tensor constant_pad_nd(const at::Tensor & self, at::IntArrayRef pad, at::Scalar value);
                                                             ~~~~^
/home/chriso/src/clion_pytorch_stuff/pytorch/xla/torch_xla/csrc/aten_xla_type_default.h:132:61: error: no type named 'MemoryFormat' in                                                         
      namespace 'at'
  static at::Tensor contiguous(const at::Tensor & self, at::MemoryFormat memory_format);
                                                        ~~~~^
/home/chriso/src/clion_pytorch_stuff/pytorch/xla/torch_xla/csrc/aten_xla_type_default.h:133:115: error: no type named 'IntArrayRef' in                                                         
      namespace 'at'
  static at::Tensor convolution(const at::Tensor & input, const at::Tensor & weight, const at::Tensor & bias, at::IntArrayRef stride, ...
                                                                                                              ~~~~^
/home/chriso/src/clion_pytorch_stuff/pytorch/xla/torch_xla/csrc/aten_xla_type_default.h:133:139: error: no type named 'IntArrayRef' in                                                         
      namespace 'at'
  ...convolution(const at::Tensor & input, const at::Tensor & weight, const at::Tensor & bias, at::IntArrayRef stride, at::IntArrayRef padd...
```

**Comment by dlibenzi** [comment]
Hi Chris, you will be really up for a painful task, if you are planning to keep pytorch/xla pinned at a given version, and move pytorch HEAD.

**Comment by cjolivier01** [comment]
It certainly is painful :)

I am not looking to move pytorch HEAD.  I am looking for, given tf1.14 release commit (or something very close to it), what commit of pytorch/xla and pytorch can I use?  I see there's a commit file that can be used to set pytorch commit (starts with a dot), but it isn't included in the repo, and the dates when new a pytorch commit is pulled in as a parent to your xla is not clear to me, so it's a lot of trial and error (mostly error :) )

**Comment by dlibenzi** [comment]
If you know that date of the last pytorch/xla commit that works with 1.14 (it seems you do), that should be pretty easy, no?
Just look at pytorch commit log and pick the lower-bound.

**Comment by cjolivier01** [comment]
You mean the commit just before the pytorch/xla commit that uses the tf I want? Tried that maybe 50 times already for various commits, sliding both xla commit and pytorch commit back and forth (pytorch alays equal to or lagging xla commit) with no success.  I am literally no closer than I was two weeks ago.

**Comment by dlibenzi** [comment]
Our tests (and the pre-submit of both pytorch and pytorch/xla running on CircleCI, run HEAD-to-HEAD.
So for a given pytorch/xla HEAD you should be able to find a matching pytorch HEAD.
It might have happened that the tests were temporarily red at that time, but that is usually not a normal condition.

**Comment by cjolivier01** [comment]
Thanks, that's good to know, I will keep this in mind during selection.

**Comment by cjolivier01** [comment]
I fried my Ubuntu desktop yesterday and rebuilt it this morning and now everything magically builds wonderfully. Thanks!
