### ISSUE TITLE
gradient checkpointing failed in xla_device

### ISSUE THREAD

**Issue by bmeoaountiful** [pytorch/xla#5766]
## ❓ Questions and Help
I try to fine-tune a large language model on xla_device, these models come from huggingface. The error is reported
```
Traceback (most recent call last):
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/site-packages/torch_xla/runtime.py", line 85, in wrapper
    return fn(*args, **kwargs)
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/site-packages/torch_xla/_internal/pjrt.py", line 75, in _run_thread_per_device
    replica_results = list(
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/site-packages/torch_xla/_internal/pjrt.py", line 68, in _thread_fn
    return fn()
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/site-packages/torch_xla/_internal/pjrt.py", line 184, in __call__
    self.fn(runtime.global_ordinal(), *self.args, **self.kwargs)
  File "/projs/framework/root/llm2/fine-tune/fine-tune.py", line 196, in _mp_fn
    train()
  File "/projs/framework/root/llm2/fine-tune/fine-tune.py", line 193, in train
    train_loop_fn(train_device_loader, epoch)
  File "/projs/framework/root/llm2/fine-tune/fine-tune.py", line 184, in train_loop_fn
    output = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/root/.cache/huggingface/modules/transformers_modules/modeling_llm.py", line 692, in forward
    outputs = self.model(
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/root/.cache/huggingface/modules/transformers_modules/modeling_llm.py", line 459, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 457, in checkpoint
    next(gen)
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 1157, in _checkpoint_without_reentrant_generator
    device_module = _get_device_module(device)
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 67, in _get_device_module
    device_module = getattr(torch, device)
  File "/home/root/.conda/envs/torch-xla/lib/python3.8/site-packages/torch/__init__.py", line 1833, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute 'xla'
```
The function torch.utils.checkpoint.checkpoint decorated with _disable_dynamo.
https://github.com/pytorch/pytorch/blob/0d95378341b4eb19849295c7ccab08cc9be328a7/torch/utils/checkpoint.py#L341
Does this mean that if the model's device is set to xla, then  torch.utils.checkpoint.checkpoint cannot be used?
If so, are there any alternative approaches to avoid using gradient checkpoint in LLM?
Any help on this would be greatly appreciated!

fine-tune.py
```
import os
import math
import pathlib
from typing import Optional, Dict
from dataclasses import dataclass, field
import json

import torch
from torch.utils.data import Dataset
import transformers
from transformers.training_args import TrainingArguments

import torch_xla
from torch_xla import runtime as xr
import torch_xla.core.xla_model as xm
import torch_xla.debug.metrics as met
import torch_xla.debug.profiler as xp
import torch_xla.distributed.parallel_loader as pl
import torch_xla.distributed.xla_backend
import torch_xla.distributed.xla_multiprocessing as xmp

@dataclass
class ModelArguments:
    model_name_or_path: Optional[str] = field(default="baichuan-inc/Baichuan2-7B-Base")

@dataclass
class DataArguments:
    data_path: str = field(
        default=None, metadata={"help": "Path to the training data."}
    )

@dataclass
class TrainingArguments(transformers.TrainingArguments):
    cache_dir: Optional[str] = field(default=None)
    optim: str = field(default="adamw_torch")
    model_max_length: int = field(
        default=512,
        metadata={
            "help": "Maximum sequence length. Sequences will be right padded (and possibly truncated)."
        },
    )
    use_lora: bool = field(default=False)


class SupervisedDataset(Dataset):
    """Dataset for supervised fine-tuning."""

    def __init__(
        self,
        data_path,
        tokenizer,
        model_max_length,
        user_tokens=[195],
        assistant_tokens=[196],
    ):
        super(SupervisedDataset, self).__init__()
        self.data = json.load(open(data_path))
        self.tokenizer = tokenizer
        self.model_max_length = model_max_length
        self.user_tokens = user_tokens
        self.assistant_tokens = assistant_tokens
        self.ignore_index = -100
        item = self.preprocessing(self.data[0])
        labels = []
        for id_ in item["labels"]:
            if id_ == -100:
                continue

            labels.append(id_)

    def __len__(self):
        return len(self.data)

    def preprocessing(self, example):
        input_ids = []
        labels = []

        for message in example["conversations"]:
            from_ = message["from"]
            value = message["value"]
            value_ids = self.tokenizer.encode(value)

            if from_ == "human":
                input_ids += self.user_tokens + value_ids
                labels += [self.tokenizer.eos_token_id] + [self.ignore_index] * len(
                    value_ids
                )
            else:
                input_ids += self.assistant_tokens + value_ids
                labels += [self.ignore_index] + value_ids
        input_ids.append(self.tokenizer.eos_token_id)
        labels.append(self.tokenizer.eos_token_id)
        input_ids = input_ids[: self.model_max_length]
        labels = labels[: self.model_max_length]
        input_ids += [self.tokenizer.pad_token_id] * (
            self.model_max_length - len(input_ids)
        )
        labels += [self.ignore_index] * (self.model_max_length - len(labels))
        input_ids = torch.LongTensor(input_ids)
        labels = torch.LongTensor(labels)
        attention_mask = input_ids.ne(self.tokenizer.pad_token_id)
        return {
            "input_ids": input_ids,
            "labels": labels,
            "attention_mask": attention_mask,
        }

    def __getitem__(self, idx) -> Dict[str, torch.Tensor]:
        return self.preprocessing(self.data[idx])

def train():
    device = xm.xla_device()
    parser = transformers.HfArgumentParser(
        (ModelArguments, DataArguments, TrainingArguments)
    )
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()

    model = transformers.AutoModelForCausalLM.from_pretrained(
        model_args.model_name_or_path,
        trust_remote_code=True,
        cache_dir=training_args.cache_dir,
    ).to(device)

    print('model device:', model.device)
    tokenizer = transformers.AutoTokenizer.from_pretrained(
        model_args.model_name_or_path,
        trust_remote_code=True,
        use_fast=False,
        model_max_length=training_args.model_max_length,
        cache_dir=training_args.cache_dir,
    )
#    if training_args.use_lora:
#        from peft import LoraConfig, TaskType, get_peft_model
#
#        peft_config = LoraConfig(
#            task_type=TaskType.CAUSAL_LM,
#            target_modules=["W_pack"],
#            inference_mode=False,
#            r=1,
#            lora_alpha=32,
#            lora_dropout=0.1,
#        )
#        model.enable_input_require_grads()
#        model = get_peft_model(model, peft_config)
#        model.print_trainable_parameters()

    dataset = SupervisedDataset(
        data_args.data_path, tokenizer, training_args.model_max_length
    )

    data_loader = torch.utils.data.DataLoader(
        dataset,
        batch_size=training_args.per_device_train_batch_size,
        shuffle=True,
        num_workers=8,
        persistent_workers=False,
        prefetch_factor=16)

    torch.manual_seed(training_args.seed)
    optimizer = torch.optim.AdamW(model.parameters(), lr=training_args.learning_rate,
                                  betas=(training_args.adam_beta1, training_args.adam_beta2),
                                  eps=training_args.adam_epsilon, weight_decay=training_args.weight_decay)

    train_device_loader = pl.MpDeviceLoader(
        data_loader,
        device,
        loader_prefetch_size=8,
        device_prefetch_size=4,
        host_to_device_transfer_threads=8)

    def train_loop_fn(loader, epoch):
        tracker = xm.RateTracker()
        model.train()
        for step, batch in enumerate(loader):
          input_ids = batch["input_ids"]
          attention_mask = batch["attention_mask"]
          labels = batch["labels"]
          with xp.StepTrace('train_baichuan2-13b-chat'):
            with xp.Trace('build_graph'):
              optimizer.zero_grad()
              output = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
              loss = output.loss
              loss.backward()
              xm.optimizer_step(optimizer)
              tracker.add(training_args.per_device_train_batch_size)

    for epoch in range(1, int(training_args.num_train_epochs)):
      train_loop_fn(train_device_loader, epoch)

def _mp_fn(index):
    train()


if __name__ == "__main__":
    xmp.spawn(_mp_fn, args=(), nprocs=None)
```
fine-tune.py can be run by executing the command
```
GPU_NUM_DEVICES=1 PJRT_DEVICE=CUDA python3 fine-tune.py  \
    --report_to "none" \
    --data_path "Baichuan2-13B-Chat/data/belle_chat_ramdon_10k.json" \
    --model_name_or_path "Baichuan2-13B-Chat/models--baichuan-inc--Baichuan2-13B-Chat/snapshots/8f6e343d545c503b91429582231d1d354dac2740/" \
    --output_dir "output" \
    --model_max_length 512 \
    --num_train_epochs 4 \
    --per_device_train_batch_size 16 \
    --gradient_accumulation_steps 1 \
    --save_strategy epoch \
    --learning_rate 2e-5 \
    --lr_scheduler_type constant \
    --adam_beta1 0.9 \
    --adam_beta2 0.98 \
    --adam_epsilon 1e-8 \
    --max_grad_norm 1.0 \
    --weight_decay 1e-4 \
    --warmup_ratio 0.0 \
    --logging_steps 1 \
    --gradient_checkpointing False \
    --bf16 False \
    --tf32 False
```

dataset: https://github.com/baichuan-inc/Baichuan2/tree/main/fine-tune/data
model: https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat/tree/main
torch version: Version: 2.1.0
torch-xla:2.1.0

**Comment by JackCaoG** [comment]
we used https://github.com/pytorch/xla/blob/master/torch_xla/utils/checkpoint.py but it is pretty much copied from upstream and add the `optimization_barrier` that prevent compiler CSE to remove the gradient checkpoint. If upstream gradient checkpoint code has the `_disable_dynamo ` there must be a reason and I expect our code to run into the same issue.

**Comment by bmeoaountiful** [comment]
it works, after convert `torch.utils.checkpoint.checkpoint` to `torch_xla.utils.checkpoint.checkpoint`. 

I'm confused whether `torch-xla.utils.checkpoint.checkpoint` reduces memory usage like `torch.util.checkpoint.checkpoint`. "The model can be executed in Torch, but encounters an OOM('out of memory') issue on XLA."

**Comment by bmeoaountiful** [comment]
it works, convert `torch.utils.checkpoint.checkpoint` to `torch_xla.utils.checkpoint.checkpoint`

**Comment by jeffhataws** [comment]
@JackCaoG, here the work-around was to switch from torch.utils.checkpoint.checkpoint to torch_xla.utils.checkpoint.checkpoint. However, it would be better to restore the ability to use torch.utils.checkpoint.checkpoint  which was working in 1.13. What are your thoughts?

**Comment by JackCaoG** [comment]
IMO `torch.utils.checkpoint.checkpoint` won't do anything because XLA compiler's CSE(common-subexpression elimination) pass will undo the gradident checkpointing. We should somehow upstream our changes so user can use `torch.utils.checkpoint.checkpoint` properly through, we currently don't have resource for that.

**Comment by steveepreston** [comment]
Still facing `AttributeError: module 'torch' has no attribute 'xla'` when running on TPU v5e env

**Comment by steveepreston** [comment]
PyTorch version: 2.6.0+cu124
Torch XLA version: 2.6.0+libtpu

<details>
<summary>Full Logs (Click to Expand):</summary>

```python
----> 1 trainer.train()

File /usr/local/lib/python3.10/site-packages/transformers/trainer.py:2328, in Trainer.train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   2326         hf_hub_utils.enable_progress_bars()
   2327 else:
-> 2328     return inner_training_loop(
   2329         args=args,
   2330         resume_from_checkpoint=resume_from_checkpoint,
   2331         trial=trial,
   2332         ignore_keys_for_eval=ignore_keys_for_eval,
   2333     )

File /usr/local/lib/python3.10/site-packages/transformers/trainer.py:2672, in Trainer._inner_training_loop(self, batch_size, args, resume_from_checkpoint, trial, ignore_keys_for_eval)
   2665 context = (
   2666     functools.partial(self.accelerator.no_sync, model=model)
   2667     if i != len(batch_samples) - 1
   2668     and self.accelerator.distributed_type != DistributedType.DEEPSPEED
   2669     else contextlib.nullcontext
   2670 )
   2671 with context():
-> 2672     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
   2674 if (
   2675     args.logging_nan_inf_filter
   2676     and not is_torch_xla_available()
   2677     and (torch.isnan(tr_loss_step) or torch.isinf(tr_loss_step))
   2678 ):
   2679     # if loss is nan or inf simply add the average of previous logged losses
   2680     tr_loss = tr_loss + tr_loss / (1 + self.state.global_step - self._globalstep_last_logged)

File /usr/local/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:1189, in SFTTrainer.training_step(self, *args, **kwargs)
   1187 def training_step(self, *args, **kwargs):
   1188     with self.maybe_activation_offload_context:
-> 1189         return super().training_step(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/transformers/trainer.py:4009, in Trainer.training_step(self, model, inputs, num_items_in_batch)
   4006     return loss_mb.reduce_mean().detach().to(self.args.device)
   4008 with self.compute_loss_context_manager():
-> 4009     loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
   4011 del inputs
   4012 if (
   4013     self.args.torch_empty_cache_steps is not None
   4014     and self.state.global_step % self.args.torch_empty_cache_steps == 0
   4015 ):

File /usr/local/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:1103, in SFTTrainer.compute_loss(self, model, inputs, return_outputs, num_items_in_batch)
   1101 # If not set, defaults from model config and may warn since cache isn't compatible with gradient checkpointing
   1102 inputs["use_cache"] = False
-> 1103 (loss, outputs) = super().compute_loss(
   1104     model, inputs, return_outputs=True, num_items_in_batch=num_items_in_batch
   1105 )
   1107 # Add auxiliary loss if available
   1108 if self.aux_loss_enabled and self.aux_loss_coef:

File /usr/local/lib/python3.10/site-packages/transformers/trainer.py:4099, in Trainer.compute_loss(self, model, inputs, return_outputs, num_items_in_batch)
   4097         kwargs["num_items_in_batch"] = num_items_in_batch
   4098     inputs = {**inputs, **kwargs}
-> 4099 outputs = model(**inputs)
   4100 # Save past state if it exists
   4101 # TODO: this needs to be fixed and made cleaner later.
   4102 if self.args.past_index >= 0:

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1739, in Module._wrapped_call_impl(self, *args, **kwargs)
   1737     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1738 else:
-> 1739     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1750, in Module._call_impl(self, *args, **kwargs)
   1745 # If we don't have any hooks, we want to skip the rest of the logic in
   1746 # this function, and just call forward.
   1747 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1748         or _global_backward_pre_hooks or _global_backward_hooks
   1749         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1750     return forward_call(*args, **kwargs)
   1752 result = None
   1753 called_always_called_hooks = set()

File /usr/local/lib/python3.10/site-packages/torch_xla/experimental/spmd_fully_sharded_data_parallel.py:160, in SpmdFullyShardedDataParallel.forward(self, *args, **kwargs)
    159 def forward(self, *args: Any, **kwargs: Any) -> torch.Tensor:
--> 160   output = self.module(*args, **kwargs)
    161   # Need to shard the output of the forward to instruct the compiler
    162   # to enforce the FSDP algorithm.
    163   self._shard_output(output, self._mesh)

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1739, in Module._wrapped_call_impl(self, *args, **kwargs)
   1737     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1738 else:
-> 1739     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1845, in Module._call_impl(self, *args, **kwargs)
   1842     return inner()
   1844 try:
-> 1845     return inner()
   1846 except Exception:
   1847     # run always called hooks if they have not already been run
   1848     # For now only forward hooks have the always_call option but perhaps
   1849     # this functionality should be added to full backward hooks as well.
   1850     for hook_id, hook in _global_forward_hooks.items():

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1793, in Module._call_impl.<locals>.inner()
   1790     bw_hook = BackwardHook(self, full_backward_hooks, backward_pre_hooks)
   1791     args = bw_hook.setup_input_hook(args)
-> 1793 result = forward_call(*args, **kwargs)
   1794 if _global_forward_hooks or self._forward_hooks:
   1795     for hook_id, hook in (
   1796         *_global_forward_hooks.items(),
   1797         *self._forward_hooks.items(),
   1798     ):
   1799         # mark that always called hook is run

File /usr/local/lib/python3.10/site-packages/peft/peft_model.py:1850, in PeftModelForCausalLM.forward(self, input_ids, attention_mask, inputs_embeds, labels, output_attentions, output_hidden_states, return_dict, task_ids, **kwargs)
   1848     with self._enable_peft_forward_hooks(**kwargs):
   1849         kwargs = {k: v for k, v in kwargs.items() if k not in self.special_peft_forward_args}
-> 1850         return self.base_model(
   1851             input_ids=input_ids,
   1852             attention_mask=attention_mask,
   1853             inputs_embeds=inputs_embeds,
   1854             labels=labels,
   1855             output_attentions=output_attentions,
   1856             output_hidden_states=output_hidden_states,
   1857             return_dict=return_dict,
   1858             **kwargs,
   1859         )
   1861 batch_size = _get_batch_size(input_ids, inputs_embeds)
   1862 if attention_mask is not None:
   1863     # concat prompt attention mask

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1739, in Module._wrapped_call_impl(self, *args, **kwargs)
   1737     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1738 else:
-> 1739     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1750, in Module._call_impl(self, *args, **kwargs)
   1745 # If we don't have any hooks, we want to skip the rest of the logic in
   1746 # this function, and just call forward.
   1747 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1748         or _global_backward_pre_hooks or _global_backward_hooks
   1749         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1750     return forward_call(*args, **kwargs)
   1752 result = None
   1753 called_always_called_hooks = set()

File /usr/local/lib/python3.10/site-packages/peft/tuners/tuners_utils.py:222, in BaseTuner.forward(self, *args, **kwargs)
    221 def forward(self, *args: Any, **kwargs: Any):
--> 222     return self.model.forward(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/transformers/utils/generic.py:940, in can_return_tuple.<locals>.wrapper(self, *args, **kwargs)
    938 if return_dict_passed is not None:
    939     return_dict = return_dict_passed
--> 940 output = func(self, *args, **kwargs)
    941 if not return_dict and not isinstance(output, tuple):
    942     output = output.to_tuple()

File /usr/local/lib/python3.10/site-packages/transformers/models/gemma2/modeling_gemma2.py:547, in Gemma2ForCausalLM.forward(self, input_ids, attention_mask, position_ids, past_key_values, inputs_embeds, labels, use_cache, output_attentions, output_hidden_states, cache_position, logits_to_keep, **kwargs)
    543 output_hidden_states = (
    544     output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
    545 )
    546 # decoder outputs consists of (dec_features, layer_state, dec_hidden, dec_attn)
--> 547 outputs: BaseModelOutputWithPast = self.model(
    548     input_ids=input_ids,
    549     attention_mask=attention_mask,
    550     position_ids=position_ids,
    551     past_key_values=past_key_values,
    552     inputs_embeds=inputs_embeds,
    553     use_cache=use_cache,
    554     output_attentions=output_attentions,
    555     output_hidden_states=output_hidden_states,
    556     cache_position=cache_position,
    557     **kwargs,
    558 )
    560 hidden_states = outputs.last_hidden_state
    561 # Only compute necessary logits, and do not upcast them to float if we are not computing the loss

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1739, in Module._wrapped_call_impl(self, *args, **kwargs)
   1737     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1738 else:
-> 1739     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1750, in Module._call_impl(self, *args, **kwargs)
   1745 # If we don't have any hooks, we want to skip the rest of the logic in
   1746 # this function, and just call forward.
   1747 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1748         or _global_backward_pre_hooks or _global_backward_hooks
   1749         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1750     return forward_call(*args, **kwargs)
   1752 result = None
   1753 called_always_called_hooks = set()

File /usr/local/lib/python3.10/site-packages/transformers/utils/generic.py:1064, in check_model_inputs.<locals>.wrapper(self, *args, **kwargs)
   1061                 module.forward = make_capture_wrapper(module, original_forward, key, specs.index)
   1062                 monkey_patched_layers.append((module, original_forward))
-> 1064 outputs = func(self, *args, **kwargs)
   1065 # Restore original forward methods
   1066 for module, original_forward in monkey_patched_layers:

File /usr/local/lib/python3.10/site-packages/transformers/models/gemma2/modeling_gemma2.py:457, in Gemma2Model.forward(self, input_ids, attention_mask, position_ids, past_key_values, inputs_embeds, use_cache, output_attentions, output_hidden_states, cache_position, **kwargs)
    454 if output_hidden_states:
    455     all_hidden_states += (hidden_states,)
--> 457 layer_outputs = decoder_layer(
    458     hidden_states,
    459     position_embeddings=position_embeddings,
    460     attention_mask=causal_mask_mapping[decoder_layer.attention_type],
    461     position_ids=position_ids,
    462     past_key_values=past_key_values,
    463     output_attentions=output_attentions,
    464     use_cache=use_cache,
    465     cache_position=cache_position,
    466     **kwargs,
    467 )
    469 hidden_states = layer_outputs[0]
    471 if output_attentions:

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1739, in Module._wrapped_call_impl(self, *args, **kwargs)
   1737     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1738 else:
-> 1739     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1750, in Module._call_impl(self, *args, **kwargs)
   1745 # If we don't have any hooks, we want to skip the rest of the logic in
   1746 # this function, and just call forward.
   1747 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1748         or _global_backward_pre_hooks or _global_backward_hooks
   1749         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1750     return forward_call(*args, **kwargs)
   1752 result = None
   1753 called_always_called_hooks = set()

File /usr/local/lib/python3.10/site-packages/torch_xla/experimental/spmd_fully_sharded_data_parallel.py:160, in SpmdFullyShardedDataParallel.forward(self, *args, **kwargs)
    159 def forward(self, *args: Any, **kwargs: Any) -> torch.Tensor:
--> 160   output = self.module(*args, **kwargs)
    161   # Need to shard the output of the forward to instruct the compiler
    162   # to enforce the FSDP algorithm.
    163   self._shard_output(output, self._mesh)

File /usr/local/lib/python3.10/site-packages/transformers/modeling_layers.py:93, in GradientCheckpointingLayer.__call__(self, *args, **kwargs)
     90         message = message.rstrip(",") + "."
     91         logger.warning_once(message)
---> 93     return self._gradient_checkpointing_func(partial(super().__call__, **kwargs), *args)
     94 return super().__call__(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/torch/_compile.py:32, in _disable_dynamo.<locals>.inner(*args, **kwargs)
     29     disable_fn = torch._dynamo.disable(fn, recursive)
     30     fn.__dynamo_disable = disable_fn
---> 32 return disable_fn(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py:745, in DisableContext.__call__.<locals>._fn(*args, **kwargs)
    741 prior_skip_guard_eval_unsafe = set_skip_guard_eval_unsafe(
    742     _is_skip_guard_eval_unsafe_stance()
    743 )
    744 try:
--> 745     return fn(*args, **kwargs)
    746 finally:
    747     _maybe_set_eval_frame(prior)

File /usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py:489, in checkpoint(function, use_reentrant, context_fn, determinism_check, debug, *args, **kwargs)
    484     if context_fn is not noop_context_fn or debug is not False:
    485         raise ValueError(
    486             "Passing `context_fn` or `debug` is only supported when "
    487             "use_reentrant=False."
    488         )
--> 489     return CheckpointFunction.apply(function, preserve, *args)
    490 else:
    491     gen = _checkpoint_without_reentrant_generator(
    492         function, preserve, context_fn, determinism_check, debug, *args, **kwargs
    493     )

File /usr/local/lib/python3.10/site-packages/torch/autograd/function.py:575, in Function.apply(cls, *args, **kwargs)
    572 if not torch._C._are_functorch_transforms_active():
    573     # See NOTE: [functorch vjp and autograd interaction]
    574     args = _functorch.utils.unwrap_dead_wrappers(args)
--> 575     return super().apply(*args, **kwargs)  # type: ignore[misc]
    577 if not is_setup_ctx_defined:
    578     raise RuntimeError(
    579         "In order to use an autograd.Function with functorch transforms "
    580         "(vmap, grad, jvp, jacrev, ...), it must override the setup_context "
    581         "staticmethod. For more details, please see "
    582         "https://pytorch.org/docs/main/notes/extending.func.html"
    583     )

File /usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py:243, in CheckpointFunction.forward(ctx, run_function, preserve_rng_state, *args)
    238 # Don't eagerly initialize the cuda context by accident.
    239 # (If the user intends that the context is initialized later, within their
    240 # run_function, we SHOULD actually stash the cuda state here.  Unfortunately,
    241 # we have no way to anticipate this will happen before we run the function.)
    242 ctx.had_device_in_fwd = False
--> 243 device_module = _get_device_module(ctx.device_type)
    244 if getattr(device_module, "_initialized", False):
    245     ctx.had_device_in_fwd = True

File /usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py:95, in _get_device_module(device)
     93 if device == "meta":
     94     return torch.device("meta")
---> 95 device_module = getattr(torch, device)
     96 return device_module

File /usr/local/lib/python3.10/site-packages/torch/__init__.py:2681, in __getattr__(name)
   2678 if name in _lazy_modules:
   2679     return importlib.import_module(f".{name}", __name__)
-> 2681 raise AttributeError(f"module '{__name__}' has no attribute '{name}'")

AttributeError: module 'torch' has no attribute 'xla'
```

</details>

**Comment by steveepreston** [comment]
Same error when:
```shell
pip install torch==2.8.0 --index-url https://download.pytorch.org/whl/cpu
pip install torch_xla[tpu]==2.8.0 -f https://storage.googleapis.com/libtpu-releases/index.html
```
```python
import torch
print(f"PyTorch version: {torch.__version__}")
import torch_xla
print(f"Torch XLA version: {torch_xla.__version__}")
```

PyTorch version: 2.8.0+cpu
Torch XLA version: 2.8.0
