### ISSUE TITLE
Colab TPU Exception in device=TPU:4: Could not run 'torchvision::nms' with arguments from the 'XLA' backend

### ISSUE THREAD

**Issue by sarmientoj24** [pytorch/xla#2587]
## 🐛 Bug

Getting this error on Colab:

```
Exception in device=TPU:4: Could not run 'torchvision::nms' with arguments from the 'XLA' backend. 'torchvision::nms' is only available for these backends: [CPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, Tracer, Autocast, Batched, VmapMode].

CPU: registered at /pytorch/vision/torchvision/csrc/vision.cpp:64 [kernel]
BackendSelect: fallthrough registered at /pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at /pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
AutogradOther: fallthrough registered at /pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:35 [backend fallback]
AutogradCPU: fallthrough registered at /pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:39 [backend fallback]
AutogradCUDA: fallthrough registered at /pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:43 [backend fallback]
AutogradXLA: fallthrough registered at /pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:47 [backend fallback]
Tracer: fallthrough registered at /pytorch/torch/csrc/jit/frontend/tracer.cpp:970 [backend fallback]
Autocast: fallthrough registered at /pytorch/aten/src/ATen/autocast_mode.cpp:254 [backend fallback]
Batched: registered at /pytorch/aten/src/ATen/BatchingRegistrations.cpp:555 [backend fallback]
VmapMode: fallthrough registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
Exception in device=TPU:2: Could not run 'torchvision::nms' with arguments from the 'XLA' backend. 'torchvision::nms' is only available for these backends: [CPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, Tracer, Autocast, Batched, VmapMode].
```

### Environment

Colab Notebook: https://colab.research.google.com/drive/1HNn5YAQTenVXkllY9cITIVYFAo8ITJBX?usp=sharing

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: 
`* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.0a0+d0df29a
	- pytorch-lightning: 0.8.1
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020`

**Comment by jysohn23** [comment]
NMS is a custom op defined by torchvision package. We only lower ops from PyTorch core, which is why you're finding there's no lowering for that in PyTorch/XLA. However, @davidel has implemented a version of it that runs natively on PyTorch/XLA with dynamic shapes:

https://github.com/pytorch/xla/blob/d5b0b4e077496bb5cfaf823cc07f6f371b1a2af6/torch_xla/core/functions.py#L87

**Comment by sarmientoj24** [comment]
@jysohn23 How do I integrate it? Do you have some idea?

**Comment by jysohn23** [comment]
Instead of calling the torchvision nms op you'd need to call our xla nms API there. Take a look at our test:

https://github.com/pytorch/xla/blob/be999bdb7ae802578805f32ef87f41e9019eb634/test/test_operations.py#L1920-L1921

**Comment by sarmientoj24** [comment]
not really sure how to do it if i am just using functions that use it.

**Comment by jysohn23** [comment]
You'd want to find where in your model you're calling NMS (if using some RCNN variant, probably in the Region Proposal Network and after the bounding box regression) and replace those calls into `torchvision::nms` with our implementation.

**Comment by sarmientoj24** [comment]
yes, it is an RCNN (see Colab code) but since there are no explicit calls, i am not sure about how

**Comment by jysohn23** [comment]
Unfortunately, we don't control the torchvision codebase ourselves, so you'll need to update the core torchvision calls into the nms.

**Comment by sarmientoj24** [comment]
i see. checking this
```selected_indices, num_valid = xf.nms(boxes, scores, score_threshold, 
                                      iou_threshold, len(BOXES)) ```
torchvision's version does not have score_threshold though

**Comment by davidel** [comment]
It probably does not use that. You can try setting that to 0 as starting point.

**Comment by sarmientoj24** [comment]
Hi @davidel 
I tried changing it 
```
return torch_xla._XLAC._xla_nms(boxes, scores, 0.01, iou_threshold,
                                  len(boxes))
```
but now I am getting an error: **AttributeError: module '_XLAC' has no attribute '_xla_nms'**
```
/usr/local/lib/python3.6/dist-packages/torch/cuda/amp/autocast_mode.py:114: UserWarning: torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-cc0da8e6b1a5> in <module>()
----> 1 trainer.fit(pd_model)

15 frames
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloader, val_dataloaders)
    929             # train
    930             if self.tpu_id is not None:
--> 931                 self.tpu_train(self.tpu_id, model)
    932             else:
    933                 xmp.spawn(self.tpu_train, args=(model,), nprocs=self.tpu_cores, start_method=start_method)

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py in tpu_train(self, tpu_core_idx, model)
    209 
    210         # continue training routine
--> 211         self.run_pretrain_routine(model)
    212 
    213         # when training ends on these platforms dump weights to get out of the main process

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py in run_pretrain_routine(self, model)
   1091 
   1092         # CORE TRAINING LOOP
-> 1093         self.train()
   1094 
   1095     def test(

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py in train(self)
    373                 # RUN TNG EPOCH
    374                 # -----------------
--> 375                 self.run_training_epoch()
    376 
    377                 if self.max_steps and self.max_steps == self.global_step:

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py in run_training_epoch(self)
    456             # RUN TRAIN STEP
    457             # ---------------
--> 458             _outputs = self.run_training_batch(batch, batch_idx)
    459             batch_result, grad_norm_dic, batch_step_metrics, batch_output = _outputs
    460 

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py in run_training_batch(self, batch, batch_idx)
    632 
    633                 # calculate loss
--> 634                 loss, batch_output = optimizer_closure()
    635 
    636                 # check if loss or model weights are nan

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py in optimizer_closure()
    594                             with torch.cuda.amp.autocast():
    595                                 output_dict = self.training_forward(split_batch, batch_idx,
--> 596                                                                     opt_idx, self.hiddens)
    597                         else:
    598                             output_dict = self.training_forward(split_batch, batch_idx, opt_idx, self.hiddens)

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py in training_forward(self, batch, batch_idx, opt_idx, hiddens)
    777             batch = self.transfer_batch_to_tpu(batch, self.tpu_id)
    778             args[0] = batch
--> 779             output = self.model.training_step(*args)
    780 
    781         # CPU forward

<ipython-input-19-1102fdafd64d> in training_step(self, batch, batch_idx)
     53     targets = [{k: v for k, v in t.items()} for t in targets]
     54     # separate losses
---> 55     loss_dict = self.model(images, targets)
     56     # total loss
     57     losses = sum(loss for loss in loss_dict.values())

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/generalized_rcnn.py in forward(self, images, targets)
     68         if isinstance(features, torch.Tensor):
     69             features = OrderedDict([('0', features)])
---> 70         proposals, proposal_losses = self.rpn(images, features, targets)
     71         detections, detector_losses = self.roi_heads(features, proposals, images.image_sizes, targets)
     72         detections = self.transform.postprocess(detections, images.image_sizes, original_image_sizes)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/rpn.py in forward(self, images, features, targets)
    491         proposals = self.box_coder.decode(pred_bbox_deltas.detach(), anchors)
    492         proposals = proposals.view(num_images, -1, 4)
--> 493         boxes, scores = self.filter_proposals(proposals, objectness, images.image_sizes, num_anchors_per_level)
    494 
    495         losses = {}

/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/rpn.py in filter_proposals(self, proposals, objectness, image_shapes, num_anchors_per_level)
    414             boxes, scores, lvl = boxes[keep], scores[keep], lvl[keep]
    415             # non-maximum suppression, independently done per level
--> 416             keep = box_ops.batched_nms(boxes, scores, lvl, self.nms_thresh)
    417             # keep only topk scoring predictions
    418             keep = keep[:self.post_nms_top_n()]

/usr/local/lib/python3.6/dist-packages/torchvision/ops/boxes.py in batched_nms(boxes, scores, idxs, iou_threshold)
     78     offsets = idxs.to(boxes) * (max_coordinate + 1)
     79     boxes_for_nms = boxes + offsets[:, None]
---> 80     keep = nms(boxes_for_nms, scores, iou_threshold)
     81     return keep
     82 

/usr/local/lib/python3.6/dist-packages/torchvision/ops/boxes.py in nms(boxes, scores, iou_threshold)
     37     """
     38     # return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
---> 39     return torch_xla._XLAC._xla_nms(boxes, scores, 0.01, iou_threshold,
     40                                   len(boxes))
     41 

AttributeError: module '_XLAC' has no attribute '_xla_nms'
```

**Comment by jysohn23** [comment]
What version of `torch_xla` are you using? The API was introduced in https://github.com/pytorch/xla/commit/d395b4bc0c52aa2facc1a9cfb9eb5371de693ec0 which is included in our 1.6 and 1.7 releases.

**Comment by sarmientoj24** [comment]
This is how I installed it @jysohn23 
```
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py --version 20200325
```

**Comment by sarmientoj24** [comment]
1.6+e788e5b
This seems to be the version

**Comment by sarmientoj24** [comment]
Okay now, I'm getting a newer error
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-50-cc0da8e6b1a5> in <module>()
----> 1 trainer.fit(pd_model)

9 frames
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloader, val_dataloaders)
    929             # train
    930             if self.tpu_id is not None:
--> 931                 self.tpu_train(self.tpu_id, model)
    932             else:
    933                 xmp.spawn(self.tpu_train, args=(model,), nprocs=self.tpu_cores, start_method=start_method)

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py in tpu_train(self, tpu_core_idx, model)
    209 
    210         # continue training routine
--> 211         self.run_pretrain_routine(model)
    212 
    213         # when training ends on these platforms dump weights to get out of the main process

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py in run_pretrain_routine(self, model)
   1091 
   1092         # CORE TRAINING LOOP
-> 1093         self.train()
   1094 
   1095     def test(

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py in train(self)
    373                 # RUN TNG EPOCH
    374                 # -----------------
--> 375                 self.run_training_epoch()
    376 
    377                 if self.max_steps and self.max_steps == self.global_step:

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py in run_training_epoch(self)
    443         # run epoch
    444         for batch_idx, (batch, is_last_batch) in self.profiler.profile_iterable(
--> 445                 enumerate(_with_is_last(train_dataloader)), "get_train_batch"
    446         ):
    447             # stop epoch if we limited the number of training batches

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/profiler/profilers.py in profile_iterable(self, iterable, action_name)
     62             try:
     63                 self.start(action_name)
---> 64                 value = next(iterator)
     65                 self.stop(action_name)
     66                 yield value

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py in _with_is_last(iterable)
    841     See `https://stackoverflow.com/a/1630350 <https://stackoverflow.com/a/1630350>`_"""
    842     it = iter(iterable)
--> 843     last = next(it)
    844     for val in it:
    845         # yield last and has next

/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/parallel_loader.py in __next__(self)
     29 
     30   def __next__(self):
---> 31     return self.next()
     32 
     33   def __len__(self):

/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/parallel_loader.py in next(self)
     32 
     33   def __len__(self):
---> 34     return self._loader.per_device_samples()
     35 
     36   def next(self):

/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py in mark_step()
    403   padding = [0] * (2 * value.dim())
    404   idx = value.dim() - 1 - dim
--> 405   ordinal = get_ordinal()
    406   padding[2 * idx] = ordinal * size
    407   padding[2 * idx + 1] = (xrt_world_size() - 1 - ordinal) * size

RuntimeError: Aborted: Session 0891eed26517ce5c is not found.
```

**Comment by davidel** [comment]
Using `--version 20200325` brings in a March release, while the NMS op went in in May.

**Comment by sarmientoj24** [comment]
Hi @davidel I used the 20200525 version now. But I got the error above now.

**Comment by sarmientoj24** [comment]
I changed the torchvision code with
```
import torch
from torch.jit.annotations import Tuple
from torch import Tensor
import torchvision
import torch_xla
import torch_xla.core.functions as xf

@torch.jit.script
def nms(boxes, scores, iou_threshold):
    # type: (Tensor, Tensor, float) -> Tensor
    """
    Performs non-maximum suppression (NMS) on the boxes according
    to their intersection-over-union (IoU).

    NMS iteratively removes lower scoring boxes which have an
    IoU greater than iou_threshold with another (higher scoring)
    box.

    If multiple boxes have the exact same score and satisfy the IoU
    criterion with respect to a reference box, the selected box is
    not guaranteed to be the same between CPU and GPU. This is similar
    to the behavior of argsort in PyTorch when repeated values are present.

    Parameters
    ----------
    boxes : Tensor[N, 4])
        boxes to perform NMS on. They
        are expected to be in (x1, y1, x2, y2) format
    scores : Tensor[N]
        scores for each one of the boxes
    iou_threshold : float
        discards all overlapping
        boxes with IoU > iou_threshold

    Returns
    -------
    keep : Tensor
        int64 tensor with the indices
        of the elements that have been kept
        by NMS, sorted in decreasing order of scores
    """
    # return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
    return xf.nms(boxes, scores, 0, iou_threshold,
                                  len(boxes))
```

But when importing, the ff:
```
torchvision.transforms import functional as F
```

I am getting the ff error:
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-13-b89087ddbc94> in <module>()
     11 from sklearn.model_selection import train_test_split
     12 from torch.utils.data import Dataset
---> 13 from torchvision.transforms import functional as F
     14 from typing import Any, Dict, List
     15 import albumentations as A

8 frames
/usr/local/lib/python3.6/dist-packages/torchvision/__init__.py in <module>()
      3 from .extension import _HAS_OPS
      4 
----> 5 from torchvision import models
      6 from torchvision import datasets
      7 from torchvision import ops

/usr/local/lib/python3.6/dist-packages/torchvision/models/__init__.py in <module>()
     10 from .shufflenetv2 import *
     11 from . import segmentation
---> 12 from . import detection
     13 from . import video
     14 from . import quantization

/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/__init__.py in <module>()
----> 1 from .faster_rcnn import *
      2 from .mask_rcnn import *
      3 from .keypoint_rcnn import *

/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/faster_rcnn.py in <module>()
      5 import torch.nn.functional as F
      6 
----> 7 from torchvision.ops import misc as misc_nn_ops
      8 from torchvision.ops import MultiScaleRoIAlign
      9 

/usr/local/lib/python3.6/dist-packages/torchvision/ops/__init__.py in <module>()
----> 1 from .boxes import nms, box_iou
      2 from .new_empty_tensor import _new_empty_tensor
      3 from .deform_conv import deform_conv2d, DeformConv2d
      4 from .roi_align import roi_align, RoIAlign
      5 from .roi_pool import roi_pool, RoIPool

/usr/local/lib/python3.6/dist-packages/torchvision/ops/boxes.py in <module>()
      6 import torch_xla.core.functions as xf
      7 
----> 8 @torch.jit.script
      9 def nms(boxes, scores, iou_threshold):
     10     # type: (Tensor, Tensor, float) -> Tensor

/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py in script(obj, optimize, _frames_up, _rcb)
   1322             _rcb = _jit_internal.createResolutionCallbackFromFrame(_frames_up + 1)
   1323         _compile_and_register_class(obj, _rcb, qualified_name)
-> 1324         return obj
   1325     else:
   1326         _check_directly_compile_overloaded(obj)

/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py in try_compile_fn(fn, loc)
    576     # object
    577     rcb = _jit_internal.createResolutionCallbackFromClosure(fn)
--> 578     return torch.jit.script(fn, _rcb=rcb)
    579 
    580 def wrap_cpp_module(cpp_module):

/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py in script(obj, optimize, _frames_up, _rcb)
   1322             _rcb = _jit_internal.createResolutionCallbackFromFrame(_frames_up + 1)
   1323         _compile_and_register_class(obj, _rcb, qualified_name)
-> 1324         return obj
   1325     else:
   1326         _check_directly_compile_overloaded(obj)

RuntimeError: 
object has no attribute _xla_nms:
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/functions.py", line 106
    indices, and the second element being the number of valid boxes.
  """
  return torch_xla._XLAC._xla_nms(boxes, scores, score_threshold, iou_threshold,
         ~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                                  output_size)
'nms' is being compiled since it was called from 'nms'
  File "/usr/local/lib/python3.6/dist-packages/torchvision/ops/boxes.py", line 43
    """
    # return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
    return xf.nms(boxes, scores, 0, iou_threshold,
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...  <--- HERE
                                  len(boxes))
```

**Comment by davidel** [comment]
Seems like the `torch.jit.script` machinery is not OK with that.
I am not sure whether there is a way to build torchvision w/out enabling script mode.

**Comment by Clive2312** [comment]
Hi @sarmientoj24 , I'm also working on running a rcnn on torch xla. I'm not sure whether you've solved this. My approach is replacing the call to torchvision's nms with xla's nms in the rpn file, just the same as jysohn23 mentioned above. 

> You'd want to find where in your model you're calling NMS (if using some RCNN variant, probably in the Region Proposal Network and after the bounding box regression) and replace those calls into `torchvision::nms` with our implementation.

Maybe you could add a `assert(0)` in torchvision's nms function to get the whole call stack and figure out where the call to torchvision's nms happened : )

**Comment by codeislife99** [comment]
Hi, has anyone figured out how to solve this issue, None of the comments/ workarounds here seem to work for me .
