### PR TITLE
Index add new

### PR DESCRIPTION
**Pull request by JackCaoG**
This is to fix the compilation error introduced by https://github.com/pytorch/pytorch/pull/65993. Will support `alpha` properly in a separate pr.

### CODE REVIEW

**Review by bdhirsh — COMMENTED** [review]
not supporting the alpha param for now sounds good to me.

I think you'll actually need to change the `index_add_` lowering to `index_add` though, now that it's a structured kernel in core. That's probably better anyway, since we prefer pytorch/xla's lowerings to be functional, right? I think the current state is just a byproduct of the fact that the old `index_add` kernel in core was composite. I see some test failures, but my guess of what's happening now is:
- you call `aten::index_add`
- XLA doesn't have a lowering: we hit a code-generated kernel that redispatches to `aten::index_add.out`
- XLA also doesn't have a lowering for `index_add.out` so things break

**Comment by JackCaoG** [comment]
> not supporting the alpha param for now sounds good to me.
> 
> I think you'll actually need to change the `index_add_` lowering to `index_add` though, now that it's a structured kernel in core. That's probably better anyway, since we prefer pytorch/xla's lowerings to be functional, right? I think the current state is just a byproduct of the fact that the old `index_add` kernel in core was composite. I see some test failures, but my guess of what's happening now is:
> 
> * you call `aten::index_add`
> * XLA doesn't have a lowering: we hit a code-generated kernel that redispatches to `aten::index_add.out`
> * XLA also doesn't have a lowering for `index_add.out` so things break

Good point, I will do that instead

**Comment by bdhirsh** [comment]
merging now that https://github.com/pytorch/pytorch/pull/65993 has gone through
