### PR TITLE
[SPMD] Expose apply_backward_optimization_barrier

### PR DESCRIPTION
**Pull request by alanwaketan**
Summary:
This PR exposes apply_backward_optimization_barrier to the spmd namespace.

Test Plan:
N.A.

### CODE REVIEW

**Review by JackCaoG — APPROVED** [review]

**Comment by alanwaketan** [comment]
Thanks, Jack!

**Comment by bhavya01** [comment]
Should we also merge this change in the 2.4 release? I saw test failure with latest 2.4 wheel
```
[2024-07-17, 16:47:21 UTC] {logging_mixin.py:150} WARNING - Traceback (most recent call last):
  File "/home/ml-auto-solutions/transformers/examples/pytorch/language-modeling/run_clm.py", line 873, in <module>
    main()
  File "/home/ml-auto-solutions/transformers/examples/pytorch/language-modeling/run_clm.py", line 644, in main
[2024-07-17, 16:47:21 UTC] {logging_mixin.py:150} WARNING -     xs.apply_backward_optimization_barrier(model.model.layers[i])
AttributeError: module 'torch_xla.distributed.spmd' has no attribute 'apply_backward_optimization_barrier'
    ```

**Comment by bhavya01** [comment]
llama2-train-spmd

**Comment by bhavya01** [comment]
I realized that this is failing because of https://github.com/pytorch-tpu/transformers/commit/ccf5b15b81e3ef3154d7e26b78efc3ba43bf5b9a

I replaced torch_xla.experimental.xla_sharding with torch_xla.distributed.spmd in the test and 2.4 release doesn't expose apply_optimization_barrier through the latter. The test passes locally with the fix.

**Comment by alanwaketan** [comment]
Sure, can I still backport things? I might have 2-3 PRs need to be back ported still?
